name: "Deployment Actions"
description: "Creates GitHub deployment and automatically updates status on completion"
author: "JD Boivin"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  token:
    description: "GitHub token with deployment permissions"
    required: false
    default: ${{ github.token }}
  ref:
    description: "Git reference for the deployment"
    required: false
    default: ${{ github.head_ref }}
  environment:
    description: "Deployment environment name"
    required: false
    default: production
  environment-url:
    description: "URL where the deployment will be accessible"
    required: false
  action-version:
    description: "Action version (automatically set)"
    required: false
    default: ${{ github.action_ref }}

outputs:
  deployment-id:
    description: "The ID of the created deployment"

runs:
  using: "docker"
  image: "Dockerfile.boot"
  post-entrypoint: "/post-entrypoint.sh"
  post-if: "always()"
  args:
    - "--build-arg"
    - "ACTION_REF=${{ inputs.action-version }}"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_HEAD_REF: ${{ inputs.ref }}
