name: "Deployment Actions"
description: "Creates GitHub deployment and automatically updates status on completion"
author: "JD Boivin"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  token:
    description: "GitHub token with deployment permissions"
    required: false
    default: ${{ github.token }}
  ref:
    description: "Git reference for the deployment"
    required: false
    default: ${{ github.head_ref }}
  environment:
    description: "Deployment environment name"
    required: false
    default: production
  environment-url:
    description: "URL where the deployment will be accessible"
    required: false

outputs:
  deployment-id:
    description: "The ID of the created deployment"
    value: ${{ steps.main-action.outputs.deployment-id }}

runs:
  using: "composite"
  steps:
    - name: Download release assets
      uses: starburst997/release-downloader@v1
      with:
        repository: "starburst997/deployment-actions"
        tag: ${{ github.action_ref }}
        fileName: "release.zip"
        out-file-path: "${{ runner.temp }}/release"
        extract: true
        token: ${{ github.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Run main action
      id: main-action
      shell: bash
      run: |
        cd "${{ runner.temp }}/release"
        node dist/index.js
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_ENVIRONMENT_URL: ${{ inputs.environment-url }}
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Run post action
      if: always()
      shell: bash
      run: |
        cd "${{ runner.temp }}/release"
        node dist-post/index.js
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_JOB_STATUS: ${{ job.status }}
