name: Production Release

on:
  push:
    branches:
      - main

jobs:
  release-production:
    name: Build and Release Production
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: starburst997/auto-version@v1
        with:
          update-major-minor: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript and bundle
        run: npm run all

      - name: Package for release
        run: |
          mkdir -p release
          zip -r release/deployment-actions.zip action.yml dist/ dist-post/

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          artifacts: |
            release/*.zip
