name: Production Release

on:
  push:
    branches:
      - main

env:
  # Prefix used for auto-version commit messages and excluding from changelogs
  COMMIT: "chore: update docker image to"

jobs:
  release-production:
    name: Build and Release Production
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      !contains(github.event.head_commit.message, 'chore: update docker image to')
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.bot.outputs.token }}
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: starburst997/auto-version@v1
        with:
          token: ${{ steps.bot.outputs.token }}
          update-major-minor: true
          edit-file: "action.yml"
          edit-commit-message: "${{ env.COMMIT }} {version}"
          git-config: false
          git-push: false

      - name: Build and Push Docker
        uses: starburst997/docker-helm-push@v1
        with:
          version: ${{ steps.version.outputs.tag }}

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
          exclude-commits: "${{ env.COMMIT }}"
          git-push: true
