name: Production Release

on:
  push:
    branches:
      - main

jobs:
  release-production:
    name: Build and Release Production
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: starburst997/auto-version@v1
        with:
          update-major-minor: true

      - name: Build and Push Docker
        uses: starburst997/docker-helm-push@v1
        with:
          version: v${{ steps.version.outputs.version }}

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
